// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.LimelightUtility;
import frc.robot.RobotContainer;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.DriveTrain;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class turn2LimeLight extends CommandBase {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
        private final DriveTrain m_driveTrain;
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS


    public turn2LimeLight(DriveTrain subsystem) {


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        m_driveTrain = subsystem;
        addRequirements(m_driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    private double targetTurn = 0;
    private boolean targetAcquired = false;
    private boolean ledWarmUp = true;
    private boolean firstSight = true;


    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
        LimelightUtility.EnableDriverCamera(false);
        LimelightUtility.WriteDouble("ledMode", 3); // 3 = Limelight On
        m_driveTrain.zeroSensors();
        firstSight = true;
        ledWarmUp = true;
        targetTurn = 0;
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        LimelightUtility.RefreshTrackingData();
        targetAcquired = LimelightUtility.ValidTargetFound();
        if (targetAcquired && firstSight) {
            // Limelight angle
            targetTurn = getTargetTurn();
            // Adjusted angle
            targetTurn = Math.atan(Math.tan(Math.toRadians(59.6))*targetTurn/160)*100;
            System.out.print("Limelight angle=" + targetTurn);
            System.out.println(" Calculated angle=" + Math.atan(Math.tan(Math.toRadians(59.6))*targetTurn/160));
            m_driveTrain.closedLoopTurn(targetTurn);
            firstSight=false;
            ledWarmUp=false;
        } 

    }
    

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        m_driveTrain.stop();    
        
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        boolean turnComplete = m_driveTrain.closedLoopTurnComplete(targetTurn);
        return (!ledWarmUp && turnComplete);
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        
    }
    private double getTargetTurn() {
        LimelightUtility.RefreshTrackingData();
        return -LimelightUtility.TargetHorizontalOffset;
    }
}
